-- Adicionar colunas se elas não existirem na tabela 'notas'
ALTER TABLE public.notas ADD COLUMN IF NOT EXISTS arquivo_caminho text;
ALTER TABLE public.notas ADD COLUMN IF NOT EXISTS status_estoque text;
ALTER TABLE public.notas ADD COLUMN IF NOT EXISTS data_contato_vendedor date;
ALTER TABLE public.notas ADD COLUMN IF NOT EXISTS previsao_entrega date;
ALTER TABLE public.notas ADD COLUMN IF NOT EXISTS motivo_rejeicao text;

-- Adicionar colunas se elas não existirem na tabela 'itens'
ALTER TABLE public.itens ADD COLUMN IF NOT EXISTS categoria text;
ALTER TABLE public.itens ADD COLUMN IF NOT EXISTS apresentacao text;
ALTER TABLE public.itens ADD COLUMN IF NOT EXISTS volume text;

-- Adicionar colunas se elas não existirem na tabela 'historico_entregas'
-- (Geralmente criamos essa tabela do zero ou ela já tem tudo, mas por garantia)
ALTER TABLE public.historico_entregas ADD COLUMN IF NOT EXISTS motivo_pendencia text;

-- Caso a tabela historico_entregas não exista (pode ter falhado se dependia de itens que dependia de notas)
CREATE TABLE IF NOT EXISTS public.historico_entregas (
  id bigint generated by default as identity primary key,
  item_id bigint references public.itens(id) on delete cascade not null,
  data_entrega timestamp with time zone default timezone('utc'::text, now()) not null,
  quantidade_entregue numeric not null,
  motivo_pendencia text
);
