-- CRIAÇÃO DA TABELA DE NOTAS (Capa do Documento)
create table public.notas (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  numero_ne text not null,       -- Número do Empenho / Ordem
  emissor text,                  -- Fornecedor ou Órgão
  tipo_documento text default 'NOTA DE EMPENHO',
  
  data_emissao date,
  data_recebimento date,         -- Data de Chegada
  data_validade date,
  
  valor_total_teto numeric,      -- Valor total do empenho
  
  status_geral text default 'PENDENTE', -- PENDENTE, APROVADA, REJEITADA
  
  -- Campos adicionados
  arquivo_caminho text,          -- Caminho do arquivo Salvo
  status_estoque text,
  data_contato_vendedor date,
  previsao_entrega date,
  motivo_rejeicao text
);

-- CRIAÇÃO DA TABELA DE ITENS
create table public.itens (
  id bigint generated by default as identity primary key,
  nota_id bigint references public.notas(id) on delete cascade not null, -- Vinculo com a Nota
  
  descricao text not null,
  quantidade numeric default 0,
  valor_unitario numeric default 0,
  
  unidade text,       -- Ex: CX, UN (Legado/Simples)
  apresentacao text,  -- Ex: Ampola, Frasco (Detalhado)
  
  -- Campos adicionados
  volume text,        -- Ex: Caixa, Pacote (Volume de transporte)
  categoria text,     -- Ex: Medicamentos, Material de Consumo
  
  status_item text default 'PENDENTE'
);

-- CRIAÇÃO DO HISTÓRICO DE ENTREGAS
create table public.historico_entregas (
  id bigint generated by default as identity primary key,
  item_id bigint references public.itens(id) on delete cascade not null,
  
  data_entrega timestamp with time zone default timezone('utc'::text, now()) not null,
  quantidade_entregue numeric not null,
  
  motivo_pendencia text -- Razão da entrega parcial ou falta
);

-- Habilitar RLS (Segurança)
alter table public.notas enable row level security;
alter table public.itens enable row level security;
alter table public.historico_entregas enable row level security;

-- Políticas de acesso (Dev)
create policy "Acesso Total Notas" on public.notas for all using (true) with check (true);
create policy "Acesso Total Itens" on public.itens for all using (true) with check (true);
create policy "Acesso Total Historico" on public.historico_entregas for all using (true) with check (true);
